"""UCI BNN benchmarks — PDMP samplers vs HMC/NUTS, multi-split aware.

Compares four PDMP samplers (ZigZag, Sticky ZigZag, Boomerang, Sticky
Boomerang) plus optionally NumPyro NUTS on three UCI regression
datasets (Boston, Naval, Energy) and four toy 1D datasets (Hernandez
PBP cubic, gap, sharp, multiscale). All PDMP samplers use PLI thinning.

Metrics: test RMSE (standardised + original units), test mean log-lik,
mean predictive std, and per-coordinate ESS on the resampled chain.

NUTS is OFF by default — pass --include-nuts to run it.

UCI datasets are run on 5 random train/test splits (configurable).
Toy 1D datasets are pre-generated by `sazz.scripts.generate_toys` and
run as a single "split"; this keeps the runner stateless w.r.t. data
generation, and the saved toys are reproducible regardless of unrelated
code changes.

Output layout:
    datasets/toy_1d/
      <toy>.pt                # generated by generate_toys.py; carries config
    results/uci_bnn/
      <dataset>/
        split_<NN>/
          <sampler>.pt        # thinned samples + config + metrics
          metrics.json        # all sampler rows for this split
      metrics.csv             # aggregated across all (dataset, split, sampler)

Workflow:
    # First: generate the toys (one-time setup)
    python -m sazz.scripts.generate_toys

    # Default: PDMPs only, splits 0-4, all UCI datasets
    python -m sazz.scripts.uci_bnn

    # Toy datasets — no splits, single run
    python -m sazz.scripts.uci_bnn --datasets hernandez

    # Mix UCI and toy in one run
    python -m sazz.scripts.uci_bnn --datasets boston hernandez --splits 0

    # Add NUTS as a 5th sampler (slow!)
    python -m sazz.scripts.uci_bnn --datasets hernandez --include-nuts

    # NUTS only on Boston split 0 (one-shot baseline)
    python -m sazz.scripts.uci_bnn --datasets boston --splits 0 \\
                                    --samplers nuts --include-nuts

    # Resume: skip (dataset, split, sampler) combos already on disk
    python -m sazz.scripts.uci_bnn --splits 0 1 2 3 4 --resume

    # Aggregate existing per-split results into metrics.csv (no sampling)
    python -m sazz.scripts.uci_bnn --aggregate-only
"""

from __future__ import annotations

import argparse
import json
import math
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import torch

from sazz.samplers.AutomaticBoomerangSampler import AutomaticBoomerangSampler
from sazz.samplers.StickyAutomaticBoomerangSampler import (
    StickyAutomaticBoomerangSampler,
)
from sazz.samplers.AutomaticZigZagSampler_torch import AutomaticZigZagSampler
from sazz.samplers.StickyAutomaticZigZagSampler_torch import (
    StickyAutomaticZigZagSampler,
)
from sazz.models.bnn_torch import make_bnn_regression, predict_regression
from sazz.utils.bnn_utils import make_kappa_from_inclusion
from sazz.utils.warmup import tune_refresh_rate
from sazz.utils.sampling import (
    resample_boomerang_path,
    resample_boomerang_path_sticky,
    resample_zigzag_path,
    resample_zigzag_path_sticky,
)


# ===========================================================================
# Config
# ===========================================================================

torch.set_default_dtype(torch.float64)

N_SKELETON   = 100_000
N_RESAMPLE   = 50_000
N_THIN_SAVE  = 4_000
BURNIN_FRAC  = 0.2
BASE_SEED    = 42

# ZigZag dynamics knobs (Boomerang has its own internal dynamics)
T_MAX_ZZ     = 0.1
GAMMA_ZZ     = 0.01

# NUTS knobs
NUTS_WARMUP  = 1_000
NUTS_DRAWS   = 2_000

HIDDEN       = [50]

OUT_DIR      = Path("results/uci_bnn")
TOY_DIR      = Path("datasets/toy_1d")

PDMP_SAMPLER_NAMES = ("zigzag", "sticky_zigzag", "boomerang", "sticky_boomerang")
ALL_SAMPLER_NAMES  = PDMP_SAMPLER_NAMES + ("nuts",)

UCI_DATASETS = ("boston", "naval", "energy")
TOY_DATASETS = ("hernandez", "gap", "sharp", "multiscale")
ALL_DATASETS = UCI_DATASETS + TOY_DATASETS


# ===========================================================================
# Raw data loading (split-agnostic)
# ===========================================================================

def load_raw_datasets() -> dict[str, tuple[np.ndarray, np.ndarray]]:
    """Load Boston / Naval / Energy as (X, y) numpy arrays before splitting.

    Naval is left at its full size; the original 1000-sample subsample was
    not part of HL&A's protocol and made cross-paper comparison incoherent.
    """
    from sklearn.datasets import fetch_openml

    boston_raw = fetch_openml(name="boston", version=1, as_frame=True, parser="auto")
    X_boston = boston_raw.data.values.astype(float)
    y_boston = boston_raw.target.values.astype(float)

    df_naval = pd.read_csv(
        "datasets/naval_data.txt", sep=r"\s+", header=None
    )
    X_naval = df_naval.iloc[:, :16].values.astype(float)
    y_naval = df_naval.iloc[:, 16].values.astype(float)

    df_energy = pd.read_excel("datasets/energy_data.xlsx")
    X_energy = df_energy.iloc[:, :8].values.astype(float)
    y_energy = df_energy.iloc[:, 8].values.astype(float)

    return {
        "boston": (X_boston, y_boston),
        "naval":  (X_naval,  y_naval),
        "energy": (X_energy, y_energy),
    }


def make_split(name: str, X: np.ndarray, y: np.ndarray, seed: int,
               test_frac: float = 0.1) -> dict[str, Any]:
    """Apply HL&A-style preprocessing for one (dataset, seed) split.

    Standardises inputs and targets using training-set statistics only.
    Returns a dict of torch tensors plus y_std for back-transforming.
    """
    from sklearn.model_selection import train_test_split

    X_tr, X_te, y_tr, y_te = train_test_split(
        X, y, test_size=test_frac, random_state=seed
    )
    x_mean, x_std = X_tr.mean(axis=0), X_tr.std(axis=0)
    x_std[x_std == 0] = 1.0
    y_mean, y_std = y_tr.mean(), y_tr.std()

    X_tr = (X_tr - x_mean) / x_std
    X_te = (X_te - x_mean) / x_std
    y_tr = (y_tr - y_mean) / y_std
    y_te = (y_te - y_mean) / y_std

    return {
        "X_train": torch.tensor(X_tr),
        "y_train": torch.tensor(y_tr),
        "X_test":  torch.tensor(X_te),
        "y_test":  torch.tensor(y_te),
        "y_std":   float(y_std),
        "n_train": X_tr.shape[0],
        "n_test":  X_te.shape[0],
    }


# ===========================================================================
# Toy 1D datasets — loaded from disk (generated by generate_toys.py)
# ===========================================================================

def load_toy(name: str, toy_dir: Path = None) -> tuple[dict[str, Any], "BNNConfig"]:
    """Load a pre-generated toy dataset and its inline BNNConfig.

    Toys are produced by `sazz.scripts.generate_toys` and saved to
    `datasets/toy_1d/<name>.pt`. The .pt file contains the standardised
    dataset plus a "config" key holding the BNNConfig used to build the
    BNN target. We pop the config out and return both separately so the
    runner doesn't need to reach into the data dict.

    Raises FileNotFoundError if the toy hasn't been generated yet.
    """
    toy_dir = toy_dir or TOY_DIR
    path = toy_dir / f"{name}.pt"
    if not path.exists():
        raise FileNotFoundError(
            f"Toy dataset '{name}' not found at {path}. "
            f"Run: python -m sazz.scripts.generate_toys --names {name}"
        )
    data = torch.load(path, weights_only=False)
    cfg = data.pop("config")
    return data, cfg


# ===========================================================================
# Per-dataset BNN target config
# ===========================================================================

@dataclass
class BNNConfig:
    """Per-dataset target hyperparameters."""
    layer_sizes: list[int]
    activation: str = "relu"
    noise_std: float = 0.3
    prior_std_weight: float = 1.0
    prior_std_bias: float = 1.0
    fan_in_scaling: bool = True
    adam_steps: int = 5000
    prior_inclusion_weight: list[float] = field(default_factory=list)


def configs_for(input_dims: dict[str, int]) -> dict[str, BNNConfig]:
    """Build per-dataset BNNConfigs for UCI datasets.

    Toy datasets carry their own BNNConfig inline in the saved .pt file
    and are loaded via `load_toy(...)` instead.
    """
    cfgs: dict[str, BNNConfig] = {}

    if "boston" in input_dims:
        cfgs["boston"] = BNNConfig(
            layer_sizes=[input_dims["boston"], *HIDDEN, 1],
            noise_std=0.3,
            prior_inclusion_weight=[0.7, 0.7],
        )
    if "naval" in input_dims:
        cfgs["naval"] = BNNConfig(
            layer_sizes=[input_dims["naval"], *HIDDEN, 1],
            noise_std=0.01,
            prior_inclusion_weight=[0.7, 0.7],
        )
    if "energy" in input_dims:
        cfgs["energy"] = BNNConfig(
            layer_sizes=[input_dims["energy"], *HIDDEN, 1],
            noise_std=0.3,
            prior_inclusion_weight=[0.7, 0.7],
        )
    return cfgs


def build_target(data: dict[str, Any], cfg: BNNConfig):
    """Build a Laplace-referenced regression BNN target."""
    return make_bnn_regression(
        data["X_train"], data["y_train"],
        layer_sizes=cfg.layer_sizes,
        activation=cfg.activation,
        prior_std_weight=cfg.prior_std_weight,
        prior_std_bias=cfg.prior_std_bias,
        fan_in_scaling=cfg.fan_in_scaling,
        noise_std=cfg.noise_std,
        covariance_reference="laplace_diag",
        adam_steps=cfg.adam_steps,
    )


# ===========================================================================
# PDMP sampler factory
# ===========================================================================

def build_pdmp_sampler(name: str, target, cfg: BNNConfig):
    """Instantiate one of the four PDMP samplers, all with PLI thinning."""
    common = dict(grad_target=target.grad_target, D=target.D, thinning="pli")

    if name == "zigzag":
        s = AutomaticZigZagSampler(**common, t_max=T_MAX_ZZ, gamma=GAMMA_ZZ)

    elif name == "sticky_zigzag":
        kappa = make_kappa_from_inclusion(
            layer_sizes=cfg.layer_sizes,
            prior_std_weight=cfg.prior_std_weight,
            prior_inclusion_weight=cfg.prior_inclusion_weight,
            fan_in_scaling=cfg.fan_in_scaling,
        )
        s = StickyAutomaticZigZagSampler(
            **common, t_max=T_MAX_ZZ, gamma=GAMMA_ZZ, kappa=kappa
        )

    elif name == "boomerang":
        s = AutomaticBoomerangSampler(**common, refresh_rate=0.1)
        s.preprocess(x_ref=target.x_ref, Sigma_inv=target.Sigma_inv)
        info = tune_refresh_rate(s, n_pilot=200)
        print(f"      tuned refresh_rate: "
              f"{info['lambda_r_old']:.3f} -> {info['lambda_r_new']:.3f}")

    elif name == "sticky_boomerang":
        kappa = make_kappa_from_inclusion(
            layer_sizes=cfg.layer_sizes,
            prior_std_weight=cfg.prior_std_weight,
            prior_inclusion_weight=cfg.prior_inclusion_weight,
            fan_in_scaling=cfg.fan_in_scaling,
        )
        s = StickyAutomaticBoomerangSampler(
            **common, refresh_rate=1.0, kappa=kappa
        )
        s.preprocess(x_ref=target.x_ref, Sigma_inv=target.Sigma_inv)
        info = tune_refresh_rate(s, n_pilot=200)
        print(f"      tuned refresh_rate: "
              f"{info['lambda_r_old']:.3f} -> {info['lambda_r_new']:.3f}")

    else:
        raise ValueError(f"Unknown PDMP sampler: {name}")

    return s


def resample_pdmp(name: str, result: dict, x_ref_np: np.ndarray) -> np.ndarray:
    """Pick the right path-resampler for each PDMP sampler family."""
    pos = result["positions"].cpu().numpy()
    vel = result["velocities"].cpu().numpy()
    tim = result["times"].cpu().numpy()

    if name == "zigzag":
        return resample_zigzag_path(
            pos, vel, tim, N_resample=N_RESAMPLE, burnin_frac=BURNIN_FRAC
        )
    if name == "sticky_zigzag":
        return resample_zigzag_path_sticky(
            pos, vel, tim, N_resample=N_RESAMPLE, burnin_frac=BURNIN_FRAC
        )
    if name == "boomerang":
        return resample_boomerang_path(
            pos, vel, tim, x_ref_np,
            N_resample=N_RESAMPLE, burnin_frac=BURNIN_FRAC,
        )
    if name == "sticky_boomerang":
        return resample_boomerang_path_sticky(
            pos, vel, tim, x_ref_np,
            N_resample=N_RESAMPLE, burnin_frac=BURNIN_FRAC,
        )
    raise ValueError(name)


# ===========================================================================
# NUTS via NumPyro
# ===========================================================================

def run_nuts(data: dict[str, Any], cfg: BNNConfig, seed: int,
             num_warmup: int = NUTS_WARMUP,
             num_samples: int = NUTS_DRAWS) -> tuple[np.ndarray, float]:
    """Run NumPyro NUTS, return samples flattened to PDMP parameter ordering.

    The flatten order MUST match what `make_bnn_regression` produces internally
    so that `predict_regression(samples_t, X_test, target)` works on it. The
    convention used here:  [W0_flat, b0, W1_flat, b1, ...] with each W stored
    in (n_in, n_out) shape and flattened row-major.
    """
    import jax
    import jax.numpy as jnp
    import numpyro
    import numpyro.distributions as dist
    from numpyro.infer import MCMC, NUTS

    layer_sizes = cfg.layer_sizes
    activation = cfg.activation
    prior_std = cfg.prior_std_weight
    prior_std_bias = cfg.prior_std_bias
    fan_in_scaling = cfg.fan_in_scaling
    noise_std = cfg.noise_std

    X = jnp.asarray(data["X_train"].cpu().numpy())
    y = jnp.asarray(data["y_train"].cpu().numpy())

    def bnn(X, y=None):
        h = X
        for i, (n_in, n_out) in enumerate(zip(layer_sizes[:-1],
                                              layer_sizes[1:])):
            # Match make_bnn_regression's fan-in convention: divide by
            # sqrt(n_in + 1) when fan_in_scaling is on (the +1 accounts for
            # the bias unit, per HL&A).
            eff_fan_in = (n_in + 1) if fan_in_scaling else 1
            scale = prior_std / jnp.sqrt(eff_fan_in)
            W = numpyro.sample(
                f"W{i}",
                dist.Normal(jnp.zeros((n_in, n_out)), scale).to_event(2),
            )
            b = numpyro.sample(
                f"b{i}",
                dist.Normal(jnp.zeros(n_out), prior_std_bias).to_event(1),
            )
            h = h @ W + b
            if i < len(layer_sizes) - 2:
                if activation == "tanh":
                    h = jnp.tanh(h)
                elif activation == "relu":
                    h = jnp.maximum(0.0, h)
                else:
                    raise ValueError(f"Unsupported activation: {activation}")
        mean = h.squeeze(-1)
        with numpyro.plate("data", X.shape[0]):
            numpyro.sample("y", dist.Normal(mean, noise_std), obs=y)

    kernel = NUTS(bnn, target_accept_prob=0.9)
    mcmc = MCMC(kernel, num_warmup=num_warmup, num_samples=num_samples,
                num_chains=1, progress_bar=True)

    t0 = time.perf_counter()
    mcmc.run(jax.random.PRNGKey(seed), X=X, y=y)
    elapsed = time.perf_counter() - t0

    posterior = mcmc.get_samples()

    # Flatten in [W0, b0, W1, b1, ...] order, row-major within each W.
    flat_parts = []
    for i in range(len(layer_sizes) - 1):
        W = np.asarray(posterior[f"W{i}"])  # [n_samples, n_in, n_out]
        b = np.asarray(posterior[f"b{i}"])  # [n_samples, n_out]
        flat_parts.append(W.reshape(W.shape[0], -1))
        flat_parts.append(b)

    samples = np.concatenate(flat_parts, axis=1).astype(np.float64)
    return samples, elapsed


# ===========================================================================
# Metrics
# ===========================================================================

def gaussian_log_lik(y_true: torch.Tensor, mean: torch.Tensor,
                     pred_std: torch.Tensor, noise_std: float) -> torch.Tensor:
    """Mean predictive log-likelihood under N(mean, pred_std^2 + noise_std^2).

    Higher is better. To convert to PBP-style NLL on original scale, negate
    this and add log(y_std).
    """
    total_var = pred_std ** 2 + noise_std ** 2
    total_std = total_var.sqrt()
    return (
        -0.5 * ((y_true - mean) / total_std) ** 2
        - total_std.log()
        - 0.5 * math.log(2 * math.pi)
    ).mean()


def ess_per_coord(samples: torch.Tensor, max_lag: int | None = None) -> torch.Tensor:
    """Initial-positive-sequence ESS per coordinate (Geyer's IPS truncation)."""
    x = samples - samples.mean(0, keepdim=True)
    n, d = x.shape
    var = (x ** 2).mean(0)
    if max_lag is None:
        max_lag = min(n - 1, 1000)

    rho_sum = torch.zeros(d, dtype=samples.dtype)
    prev_pair = torch.full((d,), float("inf"), dtype=samples.dtype)
    active = torch.ones(d, dtype=torch.bool)

    k = 1
    while k + 1 <= max_lag:
        c_k   = (x[:n - k]     * x[k:]).mean(0)     / var.clamp(min=1e-30)
        c_kp1 = (x[:n - k - 1] * x[k + 1:]).mean(0) / var.clamp(min=1e-30)
        pair = c_k + c_kp1
        kill = active & ((pair <= 0) | (pair >= prev_pair))
        active = active & ~kill
        rho_sum = rho_sum + torch.where(active, pair, torch.zeros_like(pair))
        prev_pair = torch.where(active, pair, prev_pair)
        if not active.any():
            break
        k += 2

    tau = 1.0 + 2.0 * rho_sum
    return n / tau.clamp(min=1.0)


def evaluate(samples_t: torch.Tensor, target, data: dict[str, Any],
             noise_std: float) -> dict[str, float]:
    """Compute test metrics + chain ESS summaries."""
    mean_pred, std_pred = predict_regression(samples_t, data["X_test"], target)

    rmse_std = ((mean_pred - data["y_test"]) ** 2).mean().sqrt()
    log_lik  = gaussian_log_lik(data["y_test"], mean_pred, std_pred, noise_std)
    ess = ess_per_coord(samples_t)

    return {
        "rmse_std":      float(rmse_std),
        "rmse_orig":     float(rmse_std) * data["y_std"],
        "log_lik":       float(log_lik),                   # higher = better
        "nll_orig":      -float(log_lik) + math.log(data["y_std"]),
        "pred_std_mean": float(std_pred.mean()),
        "ess_min":       float(ess.min()),
        "ess_median":    float(ess.median()),
        "ess_mean":      float(ess.mean()),
    }


# ===========================================================================
# Persistence
# ===========================================================================

def split_dir(out_dir: Path, dataset: str, split_id: int) -> Path:
    return out_dir / dataset / f"split_{split_id:02d}"


def thin_to(samples_t: torch.Tensor, n_keep: int) -> torch.Tensor:
    """Evenly-spaced thin to at most n_keep samples."""
    n = samples_t.shape[0]
    if n <= n_keep:
        return samples_t
    idx = torch.linspace(0, n - 1, n_keep).round().long()
    return samples_t[idx]


def save_run(out_dir: Path, dataset: str, split_id: int, sampler: str,
             samples_t: torch.Tensor, target, cfg: BNNConfig,
             metrics: dict[str, float], n_skeleton_events: int,
             elapsed_sec: float, y_std: float) -> Path:
    """Persist thinned samples + everything needed to re-evaluate later."""
    sd = split_dir(out_dir, dataset, split_id)
    sd.mkdir(parents=True, exist_ok=True)
    path = sd / f"{sampler}.pt"
    payload = {
        "dataset":     dataset,
        "split_id":    split_id,
        "sampler":     sampler,
        "samples":     thin_to(samples_t, N_THIN_SAVE).cpu(),
        "x_ref":       (target.x_ref.cpu() if target is not None else None),
        "layer_sizes": cfg.layer_sizes,
        "activation":  cfg.activation,
        "noise_std":   cfg.noise_std,
        "y_std":       y_std,
        "n_skeleton":  n_skeleton_events,
        "n_resample":  N_RESAMPLE,
        "burnin_frac": BURNIN_FRAC,
        "elapsed_sec": elapsed_sec,
        "metrics":     metrics,
    }
    torch.save(payload, path)
    return path


# ===========================================================================
# Per-(dataset, split) loop
# ===========================================================================

def run_split(dataset_name: str, split_id: int, data: dict[str, Any],
              cfg: BNNConfig, out_dir: Path,
              samplers_to_run: tuple[str, ...],
              resume: bool) -> list[dict]:
    """Build the target once, run each requested sampler, evaluate, persist."""
    print(f"\n--- {dataset_name.upper()} split {split_id:02d} | "
          f"layers={cfg.layer_sizes} | act={cfg.activation} | "
          f"noise_std={cfg.noise_std} | seed={BASE_SEED + split_id} ---")

    # Build PDMP target only if at least one PDMP sampler is requested.
    needs_pdmp = any(s in PDMP_SAMPLER_NAMES for s in samplers_to_run)
    target = build_target(data, cfg) if needs_pdmp else None
    x_ref_np = target.x_ref.cpu().numpy() if target is not None else None

    if target is not None:
        print(f"  D = {target.D}")

    rows: list[dict] = []

    # MAP baseline (only if we have a target)
    if target is not None:
        map_sample = target.x_ref.unsqueeze(0)
        map_metrics = evaluate(map_sample, target, data, cfg.noise_std)
        rows.append({
            "dataset": dataset_name, "split_id": split_id, "sampler": "map",
            **map_metrics, "n_skeleton": 0, "elapsed_sec": 0.0,
        })
        print(f"  [map]              "
              f"rmse_orig={map_metrics['rmse_orig']:.4f}  "
              f"log_lik={map_metrics['log_lik']:.4f}")

    seed = BASE_SEED + split_id
    sd = split_dir(out_dir, dataset_name, split_id)

    for name in samplers_to_run:
        out_path = sd / f"{name}.pt"
        if resume and out_path.exists():
            print(f"  [{name}] skipping — exists at {out_path}")
            # Re-load metrics so they make it into the aggregate.
            payload = torch.load(out_path, weights_only=False)
            rows.append({
                "dataset": dataset_name, "split_id": split_id, "sampler": name,
                **payload["metrics"],
                "n_skeleton": payload.get("n_skeleton", 0),
                "elapsed_sec": payload.get("elapsed_sec", 0.0),
            })
            continue

        print(f"  [{name}]")
        torch.manual_seed(seed)
        np.random.seed(seed)

        if name == "nuts":
            try:
                samples_np, elapsed = run_nuts(data, cfg, seed)
            except ImportError as e:
                print(f"      NUTS dependency missing ({e}); skipping.")
                continue
            samples_t = torch.tensor(samples_np)
            n_events = samples_np.shape[0]   # reuse field for "draws"
        else:
            sampler = build_pdmp_sampler(name, target, cfg)
            t0 = time.perf_counter()
            result = sampler.sample(N=N_SKELETON, diagnostics=True)
            elapsed = time.perf_counter() - t0
            print(f"      sampled {N_SKELETON} skeleton events in {elapsed:.1f}s")
            samples_np = resample_pdmp(name, result, x_ref_np)
            samples_t = torch.tensor(samples_np)
            n_events = N_SKELETON

        # NUTS needs a target to evaluate against. If only running NUTS we
        # built no target above; build one now lazily.
        eval_target = target
        if eval_target is None:
            eval_target = build_target(data, cfg)

        metrics = evaluate(samples_t, eval_target, data, cfg.noise_std)

        print(f"      rmse_orig={metrics['rmse_orig']:.4f}  "
              f"log_lik={metrics['log_lik']:.4f}  "
              f"pred_std={metrics['pred_std_mean']:.4f}  "
              f"ess_med={metrics['ess_median']:.1f}")

        path = save_run(out_dir, dataset_name, split_id, name,
                        samples_t, eval_target, cfg,
                        metrics, n_events, elapsed, data["y_std"])
        print(f"      saved -> {path}")

        rows.append({
            "dataset": dataset_name, "split_id": split_id, "sampler": name,
            **metrics, "n_skeleton": n_events, "elapsed_sec": elapsed,
        })

    # Per-split metrics.json — quick to inspect without a CSV.
    with open(sd / "metrics.json", "w") as f:
        json.dump(rows, f, indent=2)

    return rows


# ===========================================================================
# Aggregation
# ===========================================================================

def aggregate(out_dir: Path,
              datasets: list[str] | None = None) -> pd.DataFrame:
    """Walk all split_NN directories, build a metrics DataFrame, write CSV."""
    rows: list[dict] = []
    for ds_dir in sorted(out_dir.iterdir()):
        if not ds_dir.is_dir():
            continue
        if datasets is not None and ds_dir.name not in datasets:
            continue
        for split in sorted(ds_dir.glob("split_*")):
            mj = split / "metrics.json"
            if not mj.exists():
                continue
            with open(mj) as f:
                rows.extend(json.load(f))

    df = pd.DataFrame(rows)
    if df.empty:
        print("No metrics found to aggregate.")
        return df

    csv_path = out_dir / "metrics.csv"
    df.to_csv(csv_path, index=False)
    print(f"\nWrote {csv_path}  ({len(df)} rows)")

    # Summary: mean ± stderr over splits, per (dataset, sampler)
    metric_cols = ["rmse_orig", "rmse_std", "log_lik", "nll_orig",
                   "pred_std_mean", "ess_median", "elapsed_sec"]
    metric_cols = [c for c in metric_cols if c in df.columns]
    summary = (
        df.groupby(["dataset", "sampler"])[metric_cols]
          .agg(["mean", "sem"])
          .round(4)
    )
    print("\n=== Summary (mean ± stderr over splits) ===")
    print(summary.to_string())
    return df


# ===========================================================================
# CLI
# ===========================================================================

def main():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=__doc__,
    )
    parser.add_argument(
        "--datasets", nargs="+", default=list(UCI_DATASETS),
        choices=list(ALL_DATASETS),
        help="UCI datasets are split into 5 random folds; toy 1D datasets "
             "are generated once and run as a single split.",
    )
    parser.add_argument(
        "--samplers", nargs="+", default=None,
        choices=list(ALL_SAMPLER_NAMES),
        help="Which samplers to run. Defaults to all PDMP samplers, plus "
             "NUTS only if --include-nuts is passed.",
    )
    parser.add_argument(
        "--splits", nargs="+", type=int, default=[0, 1, 2, 3, 4],
        help="Which split IDs to run for UCI datasets. Default: 0 1 2 3 4. "
             "Ignored for toy datasets (always one split).",
    )
    parser.add_argument(
        "--include-nuts", action="store_true",
        help="Include NUTS in the default sampler list. NUTS is slow.",
    )
    parser.add_argument(
        "--resume", action="store_true",
        help="Skip (dataset, split, sampler) combos whose .pt file exists.",
    )
    parser.add_argument(
        "--aggregate-only", action="store_true",
        help="Skip sampling; just walk existing per-split results into "
             "metrics.csv.",
    )
    parser.add_argument("--out", type=Path, default=OUT_DIR)
    parser.add_argument("--toy-dir", type=Path, default=TOY_DIR)
    args = parser.parse_args()

    args.out.mkdir(parents=True, exist_ok=True)

    if args.aggregate_only:
        aggregate(args.out, args.datasets)
        return

    # Resolve samplers.
    if args.samplers is None:
        samplers = list(PDMP_SAMPLER_NAMES)
        if args.include_nuts:
            samplers.append("nuts")
    else:
        samplers = list(args.samplers)
        if "nuts" in samplers and not args.include_nuts:
            print("Note: 'nuts' was explicitly requested; --include-nuts is "
                  "not required when listing samplers manually.")

    uci_to_run = [d for d in args.datasets if d in UCI_DATASETS]
    toy_to_run = [d for d in args.datasets if d in TOY_DATASETS]

    # ----- UCI: load raw, split per fold -----
    if uci_to_run:
        print("Loading raw UCI datasets...")
        raw = load_raw_datasets()
        input_dims_uci = {name: X.shape[1] for name, (X, _) in raw.items()
                          if name in uci_to_run}
        cfgs = configs_for(input_dims_uci)

        print(f"\nRunning splits {args.splits} on {uci_to_run} with "
              f"samplers {samplers}")
        for ds_name in uci_to_run:
            X, y = raw[ds_name]
            for split_id in args.splits:
                seed = BASE_SEED + split_id
                data = make_split(ds_name, X, y, seed=seed)
                run_split(ds_name, split_id, data, cfgs[ds_name],
                          args.out, tuple(samplers), resume=args.resume)

    # ----- Toy 1D: load pre-generated, run as single split -----
    if toy_to_run:
        print("\nLoading toy 1D datasets...")
        try:
            toy_pairs = {name: load_toy(name, args.toy_dir) for name in toy_to_run}
        except FileNotFoundError as e:
            print(f"\nError: {e}")
            print("\nGenerate the toy datasets first with:")
            print(f"    python -m sazz.scripts.generate_toys --names {' '.join(toy_to_run)}")
            return

        print(f"\nRunning {toy_to_run} (single split each) with "
              f"samplers {samplers}")
        for ds_name in toy_to_run:
            data, cfg = toy_pairs[ds_name]
            run_split(ds_name, 0, data, cfg,
                      args.out, tuple(samplers), resume=args.resume)

    # Aggregate at the end.
    aggregate(args.out, args.datasets)


if __name__ == "__main__":
    main()
